// app/home/page.tsx
	// Auto-generated by Theme Editor - Do not edit manually

	import PageRenderer from '@/components/PageRenderer';

	export default function GeneratedPage() {
		const pageData = {
    "isHome": true,
    "metaDescription": "Discover premium homes, luxury apartments, and land for sale in Lagos Nigeria. Buy, rent, or sell properties fast with Nigeria's trusted real estate agency. Expert agents, verified listings in Lekki, Ikoyi, Victoria Island \u0026 more.",
    "nav_bg": "transparent",
    "sections": [
      {
        "props": {},
        "type": "HeaderVar1"
      },
      {
        "props": {
          "category": "featured_listings",
          "component": "FeaturedListsingsVar1",
          "fields": "*",
          "header": "Featured Listsings",
          "name": "Featured Listsings",
          "property_type": "Residential",
          "sales_type": "For Sale",
          "size": "8",
          "status": "Active",
          "sub_header": "Here are some of our handpicked properties for you.",
          "type": "section"
        },
        "type": "FeaturedListsingsVar1"
      },
      {
        "props": {
          "category": "our_services",
          "component": "OurServicesVar1",
          "header": "What We Do At Lagos Realty",
          "name": "Our Services",
          "show_more": "Yes",
          "show_more_text": "Show More Services Now",
          "size": "6",
          "sub_header": "Our services at Lagos Realty Inc.",
          "type": "section"
        },
        "type": "OurServicesVar1"
      },
      {
        "props": {
          "category": "featured_neighborhoods",
          "component": "NeighborhoodsVar1",
          "header": "Featured Neighborhoods",
          "name": "Featured Neighborhoods",
          "show_more": "Yes",
          "show_more_text": "Show More Neighborhoods",
          "size": "6",
          "sub_header": "Explore our handpicked neighborhoods that define the best of city living.",
          "type": "section"
        },
        "type": "NeighborhoodsVar1"
      },
      {
        "props": {
          "category": "blog_posts",
          "component": "BlogsVar1",
          "header": "Latest Real Estate News",
          "name": "Blogs",
          "show_more": "Yes",
          "show_more_text": "Read All Posts",
          "size": "4",
          "sub_header": "Get Latest Real Estate News Here.",
          "type": "section"
        },
        "type": "BlogsVar1"
      }
    ],
    "slug": "/",
    "title": "Lagos Realty: Home Page",
    "uid": "home-page-001"
  };

		return <PageRenderer data={pageData} />;
	}

	// Optional: Metadata for SEO
	export async function generateMetadata() {
		return {
			title: "Lagos Realty: Home Page",
			description: "",
		};
	}