import type { Metadata } from "next";

	import "../../globals.css";
	import { Providers } from "../../GlobalRedux/providers";
	import PageLoaderMain from "@/components/PageLoaderMain";
	import { ToastContainer } from "react-toastify";
	import Script from "next/script";
	import ThemeSettings from "@/components/ThemeSettings";
	import PropertyModal from "@/components/modals/PropertyModal";
	import PopUpAds from "@/components/ads/PopUpAds";

	export const metadata: Metadata = {
	title: "Homely",
	description: "Generated by create next app",
	};

	export default async function RootLayout({
	children,
	}: Readonly<{
	children: React.ReactNode;
	}>) {
	return (
		<html lang="en">
		<head>
			<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
			<Script src={`${process.env.NEXT_PUBLIC_MLS_URL}/ads/v1/mls-hub-sdk.js`} strategy="beforeInteractive" />
			<link  href={`${process.env.NEXT_PUBLIC_MLS_URL}/ads/v1/ad-styles.css`} rel="stylesheet" />
		</head>
		<body className="antialiased dark:bg-dark-main">
			<Providers>
			<ThemeSettings theme_name="Default Theme" />
			{children}
			<PageLoaderMain />
			<PropertyModal />
			<PopUpAds />
			<ToastContainer />
			</Providers>
		</body>
		</html>
	);
	}
	